export const demoUsers = [
  {
    id: "demo-admin",
    name: "Darak Admin",
    email: "admin@darak.dz",
    role: "ADMIN",
    phone: "+213550000001"
  },
  {
    id: "demo-owner",
    name: "Yasmine B.",
    email: "owner@darak.dz",
    role: "OWNER",
    phone: "+213550000002"
  },
  {
    id: "demo-agent",
    name: "Karim Immo",
    email: "agent@darak.dz",
    role: "AGENT",
    phone: "+213550000003"
  }
] as const;

export const demoListings = [
  {
    id: "listing-hydra-rent",
    title: "شقة مفروشة للإيجار في حيدرة",
    slug: "hydra-apartment-rent",
    description: "شقة حديثة بمساحة 110م² مع موقف سيارة وشرفة قريبة من المدارس والسفارات.",
    priceDzd: 125000,
    transactionType: "RENT",
    propertyType: "APARTMENT",
    wilaya: "Algiers",
    commune: "Hydra",
    neighborhood: "Hydra Centre",
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 110,
    floor: 4,
    parking: true,
    furnished: true,
    latitude: 36.745,
    longitude: 3.04,
    verificationStatus: "APPROVED",
    ownerName: "Yasmine B.",
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Wifi", "Parking", "Balcony", "Security"],
    viewsCount: 268,
    leadsCount: 18,
    createdAt: "2026-04-08"
  },
  {
    id: "listing-oran-villa-sale",
    title: "Villa premium à vendre à Oran",
    slug: "oran-villa-sale",
    description: "Villa familiale avec jardin, garage double et finitions haut de gamme.",
    priceDzd: 46500000,
    transactionType: "SALE",
    propertyType: "VILLA",
    wilaya: "Oran",
    commune: "Bir El Djir",
    neighborhood: "Akid Lotfi",
    bedrooms: 5,
    bathrooms: 4,
    areaM2: 320,
    floor: 2,
    parking: true,
    furnished: false,
    latitude: 35.72,
    longitude: -0.58,
    verificationStatus: "APPROVED",
    ownerName: "Karim Immo",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Garden", "Garage", "Security", "Terrace"],
    viewsCount: 194,
    leadsCount: 11,
    createdAt: "2026-04-11"
  },
  {
    id: "listing-constantine-studio",
    title: "Studio à louer à Constantine",
    slug: "constantine-studio-rent",
    description: "Studio lumineux proche du tramway et des universités, idéal jeune actif.",
    priceDzd: 52000,
    transactionType: "RENT",
    propertyType: "STUDIO",
    wilaya: "Constantine",
    commune: "Constantine",
    neighborhood: "Belle Vue",
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 42,
    floor: 3,
    parking: false,
    furnished: true,
    latitude: 36.365,
    longitude: 6.6147,
    verificationStatus: "APPROVED",
    ownerName: "Yasmine B.",
    image:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Furnished", "Heating", "Caretaker"],
    viewsCount: 129,
    leadsCount: 9,
    createdAt: "2026-04-13"
  },
  {
    id: "listing-bab-ezzouar-office",
    title: "Bureau à louer à Bab Ezzouar",
    slug: "bab-ezzouar-office-rent",
    description: "Plateau de bureau flexible pour startup ou cabinet, proche de l'aéroport.",
    priceDzd: 210000,
    transactionType: "RENT",
    propertyType: "OFFICE",
    wilaya: "Algiers",
    commune: "Bab Ezzouar",
    neighborhood: "Pôle d'affaires",
    bedrooms: 0,
    bathrooms: 2,
    areaM2: 180,
    floor: 7,
    parking: true,
    furnished: false,
    latitude: 36.72,
    longitude: 3.18,
    verificationStatus: "PENDING",
    ownerName: "Karim Immo",
    image:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Elevator", "Parking", "Fiber", "Reception"],
    viewsCount: 72,
    leadsCount: 4,
    createdAt: "2026-04-18"
  },
  {
    id: "listing-blida-land-sale",
    title: "Terrain à vendre à Blida",
    slug: "blida-land-sale",
    description: "Terrain plat avec accès facile, parfait pour projet résidentiel ou promotion.",
    priceDzd: 18500000,
    transactionType: "SALE",
    propertyType: "LAND",
    wilaya: "Blida",
    commune: "Blida",
    neighborhood: "Ouled Yaich",
    bedrooms: 0,
    bathrooms: 0,
    areaM2: 640,
    floor: 0,
    parking: false,
    furnished: false,
    latitude: 36.47,
    longitude: 2.83,
    verificationStatus: "APPROVED",
    ownerName: "Yasmine B.",
    image:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    amenities: ["Road access", "Investment", "Documents ready"],
    viewsCount: 88,
    leadsCount: 6,
    createdAt: "2026-04-20"
  }
];
